### ISSUE TITLE
Credentials failure

### ISSUE THREAD

**Issue by eggbean** [heussd/mirror-to-bitbucket-github-action#1]
This looks ideal for me, but I cannot get it working. It fails on push:
```
...
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'repository'
##[debug]=> '.dotfiles'
##[debug]Result: '.dotfiles'
/usr/bin/docker run --name ghcrioheussdmirrortobitbucketgithubactionlatest_ad0[80](https://github.com/eggbean/.dotfiles/runs/7938744324?check_suite_focus=true#step:4:81)0 --label 94859b --workdir /github/workspace --rm -e INPUT_PASSWORD -e INPUT_USERNAME -e INPUT_REPOSITORY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_DEBUG -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/.dotfiles/.dotfiles":"/github/workspace" ghcr.io/heussd/mirror-to-bitbucket-github-action:latest  "eggbean" "***
" ".dotfiles"
Validating BitBucket credentials...
... failed. Most likely, the provided credentials are invalid. Terminating...
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Push
```
I had not signed into my Atlassian account, which had 2FA enabled. I first tried using an API key for `${{ secrets.BITBUCKET_PASSWORD }}` because of the 2FA, but it failed. I then used my password, which failed. I then tried to disable 2FA, but strangely it seems that 2FA is already disabled. I definitely had to use it to sign in originally and I always enable 2FA whenever it is available.

Does it need BitBucket credentials instead of Atlassian?

(I am familiar with using GitHub Actions with repository secrets)

**Comment by eggbean** [comment]
I realised that I did have 2FA on my BitBucket account (not Atlassian), which doesn't even have a password, as you sign in through Atlassian now. Confusing. I disabled that too, but it still doesn't work. I also tried adding the username and repository variables, but that didn't help.

**Comment by heussd** [comment]
Hi @eggbean,
thanks for raising an issue.

AFAIK not too much time ago, BitBucket stopped supporting username and passwords of main accounts for use cases like this. Instead, [App Passwords](https://bitbucket.org/account/settings/app-passwords/) should be used. Try to create a new one with repository-write-permissions and use the generated password for BITBUCKET_PASSWORD.

Sorry, the documentation of the action should have been updated.

**Comment by eggbean** [comment]
Hi, apologies for not getting back sooner, but I have been trying everything to get it to work. I have tried everything. I have looked at your workflow files to see where I could have made a mistake, but there is still this problem with authentication that doesn't make any sense. I have tried putting a new line after the App Password in GitHub, tried different permissions, including everything ticked, etc. Stange.

**Comment by heussd** [comment]
Hi @eggbean, I'm sorry to hear that.

I was able to reproduce your issue with a new repo and a new app password here:

[https://github.com/heussd/eggbeans-bug](https://github.com/heussd/eggbeans-bug)

Turns out the REST call to `https://api.bitbucket.org/2.0/user` plus the potential initial creation of repositories require additional permissions.

Here's the app password permissions that got my mirroring to work:

<img width="585" alt="Screenshot 2022-08-27 at 16 29 35" src="https://user-images.githubusercontent.com/887095/187037151-5326af8a-2dde-48a1-adae-85b2d3f9f0af.png">

Please let me know if this fixes the issue for you. I'll update the readme. Thanks for taking the time to improve this GitHub Action with your Feedback.
